export const DIALOG = {
  OPEN: 'DIALOG.OPEN_DIALOG',
  CLOSE: 'DIALOG.CLOSE_DIALOG',
  CLOSE_ALL: 'DIALOG.CLOSE_ALL_DIALOGS',
};

export const MAIN_DATA = {
  SUCCESS: 'MAIN_DATA.SUCCESS',
  UPDATE: 'MAIN_DATA.UPDATE',
  FAIL: 'MAIN_DATA.FAIL',
};
